
-- =================================================================
-- Database Initialization Script for Portfolio
-- Database: Oracle
-- =================================================================

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE social_links PURGE';
   EXECUTE IMMEDIATE 'DROP TABLE projects PURGE';
   EXECUTE IMMEDIATE 'DROP TABLE experiences PURGE';
   EXECUTE IMMEDIATE 'DROP TABLE users PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- =================================================================
-- TABLE STRUCTURE
-- =================================================================

-- Table 1: User (main portfolio information)
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    professional_title VARCHAR2(150) NOT NULL,
    about CLOB NOT NULL,
    location VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    is_active NUMBER(1) DEFAULT 1 NOT NULL, -- Boolean flag (0=Hidden, 1=Visible)
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_user_active CHECK (is_active IN (0, 1))
);

-- Table 2: Work Experiences
CREATE TABLE experiences (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    enterprise VARCHAR2(150) NOT NULL,
    job_title VARCHAR2(150) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    description CLOB NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL, -- Boolean flag (0=Hidden, 1=Visible)
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_exp_active CHECK (is_active IN (0, 1)),
    CONSTRAINT fk_experiences_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Table 3: Projects
CREATE TABLE projects (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(200) NOT NULL,
    description CLOB NOT NULL,
    image_url VARCHAR2(500),
    github_link VARCHAR2(500),
    demo_link VARCHAR2(500),
    technologies VARCHAR2(500), -- Separate them with commas: "React, TypeScript, OCI"
    is_active NUMBER(1) DEFAULT 1 NOT NULL, -- Boolean flag (0=Hidden, 1=Visible)
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_proj_active CHECK (is_active IN (0, 1)),
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Table 4: Social Links
CREATE TABLE social_links (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    platform VARCHAR2(50) NOT NULL, -- twitter, linkedin, github, etc
    url VARCHAR2(500) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL, -- Boolean flag (0=Hidden, 1=Visible)
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_social_active CHECK (is_active IN (0, 1)),
    CONSTRAINT fk_social_links_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Table: Certifications
CREATE TABLE certifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(200) NOT NULL,
    organization VARCHAR2(100) DEFAULT 'Oracle' NOT NULL,
    url_file VARCHAR2(500) NOT NULL, -- Link de verificación
    badge_url VARCHAR2(500),         -- Link a la imagen de la insignia (PNG/SVG)
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    issue_date DATE,
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT fk_cert_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_cert_active CHECK (is_active IN (0, 1))
);

-- =================================================================
-- SEEDING DATA
-- =================================================================

-- Insert main user
INSERT INTO users (name, professional_title, about, location, email)
VALUES ('Luis Solarte', 'Desarrollador Full Stack & Cloud Engineer', 'Apasionado por la creación de soluciones tecnológicas robustas y escalables desde cero. Con experiencia en el desarrollo de aplicaciones web modernas utilizando Next.js y TypeScript, y en la automatización de infraestructura en la nube (IaC) con Terraform en OCI. Mi objetivo es combinar un código limpio y eficiente con una infraestructura resiliente y segura.', 'Madrid, España', 'contact@luissanchez.dev');

-- Insert work experiences
INSERT INTO experiences (user_id, enterprise, job_title, start_date, end_date, description)
VALUES (1, 'Tech Solutions Inc.', 'Software Engineer', TO_DATE('2021-06-01', 'YYYY-MM-DD'), NULL, 'Desarrollo y mantenimiento de la plataforma principal de la compañía. Migración de servicios a una arquitectura de microservicios en la nube. Implementación de pipelines de CI/CD para automatizar despliegues.');

INSERT INTO experiences (user_id, enterprise, job_title, start_date, end_date, description)
VALUES (1, 'Innovate Corp.', 'Junior Developer', TO_DATE('2019-07-01', 'YYYY-MM-DD'), TO_DATE('2021-05-30', 'YYYY-MM-DD'), 'Participación en el desarrollo de aplicaciones web internas. Soporte en la resolución de incidencias y mejora continua de los sistemas existentes.');

-- Insert portfolio projects
INSERT INTO projects (user_id, name, description, image_url, github_link, demo_link, technologies)
VALUES (1, 'Mi Portafolio Profesional', 'Este mismo sitio web. Desplegado en OCI con infraestructura como código (Terraform), Docker y una base de datos autónoma. El frontend está construido con Next.js y Tailwind CSS.', '/images/projects/portfolio.jpg', 'https://github.com/your-user/my-portfolio', 'https://www.luissanchez.dev', 'Next.js, TypeScript, OCI, Terraform, Docker, Oracle DB');

INSERT INTO projects (user_id, name, description, image_url, github_link, demo_link, technologies)
VALUES (1, 'Plataforma de E-commerce', 'Una tienda online completa con carrito de compras, pasarela de pago y panel de administración. Construida con un enfoque en el rendimiento y la experiencia de usuario.', '/images/projects/ecommerce.jpg', 'https://github.com/your-user/ecommerce-project', NULL, 'React, Node.js, Express, PostgreSQL');

INSERT INTO certifications (user_id, name, organization, url_file, badge_url, is_active)
VALUES (1, 
        'Oracle Cloud Infrastructure 2024 Foundations Associate', 
        'Oracle', 
        'https://catalog-education.oracle.com/...id=TU_ID', 
        '/images/certs/oci-foundations.png', 
        1);

-- Insert social links
INSERT INTO social_links (user_id, platform, url)
VALUES (1, 'github', 'https://github.com/your-user');

INSERT INTO social_links (user_id, platform, url)
VALUES (1, 'linkedin', 'https://linkedin.com/in/your-profile');

INSERT INTO social_links (user_id, platform, url)
VALUES (1, 'twitter', 'https://twitter.com/your-handle');

-- =================================================================
-- Finalize transaction
-- =================================================================
COMMIT;
/
