-- =================================================================
-- Migration 001: Initial Schema
-- Creates all tables for the portfolio application
-- Safe to run multiple times (ignores ORA-00955 already exists)
-- =================================================================

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    professional_title VARCHAR2(150) NOT NULL,
    about CLOB NOT NULL,
    location VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_user_active CHECK (is_active IN (0, 1))
);

CREATE TABLE experiences (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    enterprise VARCHAR2(150) NOT NULL,
    job_title VARCHAR2(150) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    description CLOB NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_exp_active CHECK (is_active IN (0, 1)),
    CONSTRAINT fk_experiences_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE projects (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(200) NOT NULL,
    description CLOB NOT NULL,
    image_url VARCHAR2(500),
    github_link VARCHAR2(500),
    demo_link VARCHAR2(500),
    technologies VARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_proj_active CHECK (is_active IN (0, 1)),
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE social_links (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    platform VARCHAR2(50) NOT NULL,
    url VARCHAR2(500) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT chk_social_active CHECK (is_active IN (0, 1)),
    CONSTRAINT fk_social_links_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE certifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(200) NOT NULL,
    organization VARCHAR2(100) DEFAULT 'Oracle' NOT NULL,
    url_file VARCHAR2(500) NOT NULL,
    badge_url VARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    issue_date DATE,
    created_at TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT fk_cert_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_cert_active CHECK (is_active IN (0, 1))
);

-- Migration tracking table — records which migrations have already run
CREATE TABLE schema_migrations (
    version VARCHAR2(50) PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT SYSDATE NOT NULL
);
